/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./../src/components/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    NavBar: typeof import('./../src/components/NavBar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
    Tabbar: typeof import('./../src/components/Tabbar/index.vue')['default']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopover: typeof import('vant/es')['Popover']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
